# CMake generated Testfile for 
# Source directory: /home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load
# Build directory: /home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(usage "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-h")
set_tests_properties(usage PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;87;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(no_arguments "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load")
set_tests_properties(no_arguments PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;91;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(custom_interval "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-i" "3")
set_tests_properties(custom_interval PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;95;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(no_cpu_graph "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-g" "0")
set_tests_properties(no_cpu_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;99;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(colors "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "--colors")
set_tests_properties(colors PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;103;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(colors_short "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-c")
set_tests_properties(colors_short PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;107;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(powerline-right "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "--powerline-right")
set_tests_properties(powerline-right PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;111;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(powerline-left "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "--powerline-left")
set_tests_properties(powerline-left PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;115;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(invalid_status_interval "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-i" "-1")
set_tests_properties(invalid_status_interval PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;119;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(invalid_graph_lines "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "--graph_lines" "-2")
set_tests_properties(invalid_graph_lines PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;123;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(old_option_specification "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "2" "8")
set_tests_properties(old_option_specification PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;127;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(memory_mode_free_memory "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-m" "1")
set_tests_properties(memory_mode_free_memory PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;131;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(memory_mode_used_percentage "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-m" "2")
set_tests_properties(memory_mode_used_percentage PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;135;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(averages_count_0 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-a" "0")
set_tests_properties(averages_count_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;139;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(averages_count_1 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-a" "1")
set_tests_properties(averages_count_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;143;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(averages_count_2 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-a" "2")
set_tests_properties(averages_count_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;147;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(averages_count_3 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-a" "3")
set_tests_properties(averages_count_3 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;151;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(cpu_mode_0 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "--cpu-mode" "0")
set_tests_properties(cpu_mode_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;155;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(cpu_mode_1 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "--cpu-mode" "1")
set_tests_properties(cpu_mode_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;159;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(cpu_mode_short_0 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-t" "0")
set_tests_properties(cpu_mode_short_0 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;163;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
add_test(cpu_mode_short_1 "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" "-t" "1")
set_tests_properties(cpu_mode_short_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;167;add_test;/home/No0ne/.config/tmux/plugins/tmux-mem-cpu-load/CMakeLists.txt;0;")
